import { useEffect, useState } from 'react'
import type { Evidence, FindingCitation, PassageResponse, Run } from '../types'
import { EvidenceFindingsPanel, SourceLimitations, sliceCodepoints } from '../components/EvidenceFindingsPanel'
import { api } from '../api'
import { reportFailed, reportFailureReason } from '../researchStatus'
import { statusNames, type MapNode } from './ExecutionMap'
import { StageReader } from './StageReader'
import { RecordReferences } from './RecordReferences'
import { contentNature, savedSourceAction, sourceForm, sourceReferenceLabel } from '../contentLabels'
export type DetailTab='event'|'actors'|'report'
export function DetailPanel({run,tab,node,onClose,onClear,onSource,onCitation,onNew,onExpand,onRepair,repairing=false,presentation='panel'}:{run:Run|null;tab:DetailTab;onClose:()=>void;node:MapNode|null;onClear:()=>void;onSource:(e:Evidence)=>void;onCitation:(c:FindingCitation)=>void;onNew:()=>void;onExpand?:()=>void;onRepair?:()=>void;repairing?:boolean;presentation?:'panel'|'page'}){
 return <aside className={`detail-panel reading-${tab} ${presentation==='page'?'detail-page':''}`} aria-label="研究阅读区"><header className="reading-header"><div><small>{node?'节点记录':'研究资料'}</small><h2>{node?node.title:tab==='event'?'问题与证据':tab==='actors'?'主体与行动':'研究报告'}</h2></div><div className="reading-actions">{onExpand&&<button onClick={onExpand}>{presentation==='page'?'返回浮层阅读 ↙':'打开完整页面 ↗'}</button>}<button onClick={onClose} aria-label={presentation==='page'?'返回推演画布':'收起阅读区'}>{presentation==='page'?'← 返回推演画布':'收起 ↓'}</button></div></header><div className="detail-scroll">
  {node&&node.id==='forecast'&&<section className="selected-detail"><div className="section-line"><small>所选节点 · {node.kind}</small><button aria-label="关闭所选节点" onClick={onClear}>×</button></div><h2>{node.title}</h2><p>{node.text}</p></section>}
  {node&&run&&(node.phase!=='forecast'||node.id.startsWith('outcome:'))?<StageReader run={run} node={node} onSource={onSource} onCitation={onCitation}/>:!run?<section className="empty-detail"><span>◎</span><h2>从事件，到可检查的判断</h2><p>新建一个研究问题，确认时间边界与前提，再启动联网取证和推演。</p><button className="primary" onClick={onNew}>新建研究 →</button></section>:tab==='event'?<><div className="section-line"><h2>事件概览</h2><span className="small-state">{reportFailed(run)?'报告待修复':statusNames[run.status]||run.status}</span></div><h3>{run.question.question}</h3><dl className="event-metadata"><div><dt>信息截至</dt><dd>{new Date(run.question.as_of).toLocaleString('zh-CN')}</dd></div><div><dt>运行类型</dt><dd>{run.demo?'固定教学回放':run.evidence_mode==='online'?'联网取证': '历史材料测试'}</dd></div><div><dt>模型</dt><dd>{run.model}</dd></div></dl>{run.question.mode==='binary'&&run.question.resolution_rule&&<><h4>原研究判定口径</h4><p>{run.question.resolution_rule}</p></>}<h4>检索方向</h4><List items={run.question_analysis?.search_queries||run.question_framing?.retrieval_plan.map(t=>t.query)||[]}/><EvidenceFindingsPanel framing={run.question_framing} assessment={run.evidence_assessment} evidence={run.evidence} onInspectCitation={onCitation}/><h4>实际来源 · {run.evidence.length}</h4>{run.evidence.map(e=><button className="source-short" key={e.id} onClick={()=>onSource(e)}><small>{e.id} · {e.publisher||'未知发布方'}</small><strong>{e.title}</strong><span>{savedSourceAction(e)} ↗</span></button>)}{!run.evidence.length&&<p className="subtle">尚未取得外部来源。</p>}{run.evidence_assessment?.retrieval_log?.map(log=><div className="search-log" key={log.task_id}><strong>{log.query}</strong><span>{log.status==='failed'?`检索失败：${log.error}`:`${log.result_count} 条候选`}</span></div>)}</>:tab==='actors'?<><h2>角色与行为约束</h2><p className="subtle">主体是模型识别或构造的代表性角色；名称不证明对应机构实际存在，推演行动不代表已发生事件。</p>{run.world?.actors.length?run.world.actors.map(a=><article className="actor-detail" key={a.id}><div className="section-line"><h3>{a.name}</h3><small>{a.id}</small></div><p>{a.goal}</p><h4>资源 / 约束</h4><List items={[...a.resources,...a.constraints]}/>{run.actions.filter(action=>action.actor_id===a.id).map(action=><div className="action-detail" key={action.id}><small>{contentNature.action} · R{action.round} · 状态 {action.parent_state}</small><h4>{action.action}</h4><p>{action.rationale_summary}</p></div>)}</article>):<p>{run.world?.simulation_branch_reason||'尚未识别到行为主体，不展示虚构角色。'}</p>}<h4>模型假设</h4><List items={run.world?.assumptions.map(a=>a.content)||[]}/></>:<ReportSummary run={run} onNew={onNew} onRepair={onRepair} repairing={repairing} onSource={onSource}/>}
  {!!run?.errors.length&&<p role="alert" className="notice danger">{run.errors.join('；')}</p>}
 </div></aside>
}
export function List({items}:{items:string[]}){return items.length?<ul className="detail-list">{items.map((v,i)=><li key={i}>{v}</li>)}</ul>:<p className="subtle">暂无记录</p>}
function ReportSummary({run,onNew,onRepair,repairing,onSource}:{run:Run;onNew:()=>void;onRepair?:()=>void;repairing?:boolean;onSource:(e:Evidence)=>void}){
 const f=run.forecast
 const rejected=reportFailed(run)
 return <><div className="section-line"><h2>推演总结</h2><span className="small-state">{reportFailed(run)?'报告待修复':statusNames[run.status]||run.status}</span></div><h3 className="report-conclusion">{rejected?'自动摘要未通过质量检查':f?.conclusion||'等待最终报告'}</h3>{run.question.mode==='scenario'&&<p className="subtle">{contentNature.scenario}</p>}{f?.probabilities?<div className="probability-list">{Object.entries(f.probabilities).map(([k,v])=><div key={k}><span>{k}</span><strong>{(v*100).toFixed(1)}%</strong><meter min={0} max={1} value={v}/></div>)}<small>主观概率 · 未经校准</small></div>:<p className="notice warning">{run.question.mode==='scenario'?'情景推演 · 依据、可能路径与局限':f?'本次没有可报告的概率，保留判断。':'报告尚未生成，不提前展示概率。'}</p>}
  {rejected&&<section className="report-repair notice warning"><h4>报告未通过检查</h4><p>自动摘要未通过质量检查，未作为研究结论展示。原始推演及被拒绝的版本保留在导出记录中。</p><p>{reportFailureReason(run)}</p>{run.report_repair?.available&&onRepair?<><p>先核验现有来源和推演记录，通过后在新的研究记录中重试报告。原始记录保留。</p><button className="primary" disabled={repairing} onClick={onRepair}>{repairing?'正在检查…':'检查并重试报告 ↗'}</button></>:<p>请根据上述原因修正来源或创建后续研究。</p>}</section>}
  {!rejected&&!f?.probabilities&&run.report_repair?.available&&onRepair&&<button className="primary" disabled={repairing} onClick={onRepair}>{repairing?'正在检查…':'重新生成概率 ↗'}</button>}
  {run.parent_run_id&&!run.report_repair_parent&&<p className="notice">本研究关联了此前记录，重新取证与推演的过程见画布。<a href={`#/research/${encodeURIComponent(run.parent_run_id)}/report`}>查看原始研究 ↗</a></p>}
  {run.report_repair_parent&&<p className="notice">本报告由失败记录重新核验后生成。<a href={`#/research/${encodeURIComponent(run.report_repair_parent)}/report`}>查看原始记录 ↗</a></p>}
  {!rejected&&!!f?.scenario_details?.length&&<section className="scenario-comparison"><h3>情景定义与概率理由</h3>{f.scenario_details.map(s=><article className="scenario-detail" key={s.name}><div className="section-line"><h4>{s.name}</h4>{f.probabilities?.[s.name]!==undefined&&<strong>{(f.probabilities[s.name]*100).toFixed(1)}%</strong>}</div><p className="scenario-definition">{s.definition}</p><h5>触发条件</h5><List items={s.conditions}/><h5>相对概率与不确定性</h5><p>{s.rationale}</p><RecordReferences run={run} evidenceIds={s.evidence_ids} assumptionIds={s.assumption_ids} simulationIds={s.simulation_ids} onSource={onSource}/></article>)}</section>}
  {!rejected&&<>
  <section className="report-section"><div className="report-section-title"><span>01</span><h4>关键拐点与依据</h4></div>{(!rejected?f?.supporting:[])?.map((c,i)=><article className="conclusion-entry" key={i}><p>{c.text}</p><RecordReferences run={run} evidenceIds={c.evidence_ids} assumptionIds={c.assumption_ids} simulationIds={c.simulation_ids} onSource={onSource}/></article>)}{!f?.supporting.length&&<p className="subtle">暂无可报告的支持依据。</p>}</section>
  <section className="report-section"><div className="report-section-title"><span>02</span><h4>未选之路与反对依据</h4></div>{(!rejected?f?.opposing:[])?.map((c,i)=><article className="conclusion-entry" key={i}><p>{c.text}</p><RecordReferences run={run} evidenceIds={c.evidence_ids} assumptionIds={c.assumption_ids} simulationIds={c.simulation_ids} onSource={onSource}/></article>)}<List items={rejected?[]:f?.scenarios||[]}/></section>
  <section className="report-section"><div className="report-section-title"><span>03</span><h4>残余风险与审查</h4></div>{!!run.review?.issues.length&&<p className="subtle">以下是模型提出的待核查问题，不代表已证实的来源结论。</p>}{(!rejected?run.review?.issues:[])?.map((v,i)=><article className="conclusion-entry" key={i}><strong>{v.claim}</strong><p>{v.explanation}</p></article>)}<List items={f?.limitations||[]}/></section>
  <section className="report-section"><div className="report-section-title"><span>04</span><h4>后续需要的新信息</h4></div><List items={rejected?[]:f?.new_information||[]}/><button className="text-link" onClick={onNew}>创建后续研究 ↗</button></section>
  </>}
  {(f||rejected)&&<div className="report-exports">{f&&!rejected&&<a href={`/api/runs/${run.run_id}/export?format=html`}>导出推演报告 ↗</a>}<a href={`/api/runs/${run.run_id}/export?format=json`}>导出推演记录</a></div>}
 </>
}
export function SourceReader({run,evidence,citation,onClose}:{run:Run;evidence:Evidence;citation?:FindingCitation|null;onClose:()=>void}){
 const [result,setResult]=useState<PassageResponse|null>(null),[error,setError]=useState('')
 useEffect(()=>{let current=true;setResult(null);setError('');api<PassageResponse>(`/runs/${run.run_id}/evidence/${evidence.id}/passages`).then(r=>{if(current){if(citation&&(r.snapshot_hash!==citation.snapshot_hash||sliceCodepoints(r.text,citation.start,citation.end)!==citation.quote)){setError('原文哈希或引用位置不匹配，不能高亮引用。')}else setResult(r)}}).catch(e=>{if(current)setError(e.message)});return()=>{current=false}},[run.run_id,evidence.id,citation])
 return <section className="source-dialog"><header><div><small>{sourceReferenceLabel(evidence.id,evidence)}</small><h2>{evidence.title}</h2></div><button onClick={onClose} aria-label="关闭来源原文">×</button></header><div className="dialog-body"><p className="notice warning">{sourceForm(evidence)==='snippet'?'当前只有搜索摘要，未取得完整网页正文。':'以下是当次保存的来源文本。'}{!evidence.published_at?' 发布时间未知。':''}{evidence.availability==='historical_exercise'?' 历史回看材料，不是盲测。':''}</p><SourceLimitations evidence={evidence}/><p className="subtle">{evidence.source_group_basis}</p><a href={evidence.source_url||undefined} target="_blank" rel="noreferrer">打开来源网页 ↗</a>{error&&<p role="alert" className="notice danger">{error}</p>}<div className="source-body">{citation&&result?<>{sliceCodepoints(result.text,0,citation.start)}<mark>{sliceCodepoints(result.text,citation.start,citation.end)}</mark>{sliceCodepoints(result.text,citation.end,Array.from(result.text).length)}</>:result?.text||evidence.excerpt}</div></div></section>
}
